# Generated by Django 5.0.3 on 2024-04-27 17:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_profile_delete_testemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, db_column='CREATED_AT', verbose_name='Criado em')),
                ('id', models.UUIDField(db_column='CD_POST', default=uuid.uuid4, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(blank=True, db_column='UPDATED_AT', null=True, verbose_name='Atualizado em')),
                ('post_text', models.CharField(db_column='POST', max_length=500, verbose_name='Texto')),
                ('like_count', models.IntegerField(db_column='QT_LIKE', null=True, verbose_name='Quantidade de curtidas')),
                ('status', models.CharField(choices=[('public', 'Público'), ('private', 'Privado'), ('withheld', 'Retido'), ('deleted', 'Deletado')], default='public', max_length=15)),
                ('created_by', models.ForeignKey(db_column='CREATED_BY', on_delete=django.db.models.deletion.CASCADE, to='authentication.profile', verbose_name='Criado por')),
                ('likes', models.ManyToManyField(db_column='LIKE', related_name='post_likes', to='authentication.profile', verbose_name='Curtidas')),
            ],
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, db_column='PATH', upload_to='post/media', verbose_name='Imagem')),
                ('post', models.ForeignKey(db_column='CD_POST', on_delete=django.db.models.deletion.CASCADE, to='post.post', verbose_name='Postagem')),
            ],
        ),
    ]
