# Generated by Django 5.0.3 on 2024-04-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostFeedIndex',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, db_column='CREATED_AT', verbose_name='Criado em')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('index_name', models.CharField(max_length=20, unique=True)),
                ('index_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='feed_category',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
