# Generated by Django 5.0.3 on 2024-04-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_postfeedindex_post_feed_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfeedindex',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='CREATED_AT', verbose_name='Criado em'),
        ),
    ]
