# Generated by Django 5.0.3 on 2024-04-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_postfeedindex_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_count',
            field=models.IntegerField(blank=True, db_column='QT_LIKE', null=True, verbose_name='Quantidade de curtidas'),
        ),
    ]
