# Generated by Django 5.0.3 on 2024-04-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='CREATED_AT', verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='post',
            name='feed_category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
