# Generated by Django 5.0.3 on 2024-04-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_created_at_alter_post_feed_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like_count',
            field=models.IntegerField(blank=True, db_column='QT_LIKE', default=0, null=True, verbose_name='Quantidade de curtidas'),
        ),
    ]
