# Generated by Django 5.0.3 on 2024-04-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='image',
            field=models.ImageField(db_column='PATH', upload_to='post/media', verbose_name='Imagem'),
        ),
    ]
