# Generated by Django 5.0.3 on 2024-05-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_postmedia_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feed_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
