# Generated by Django 5.0.3 on 2024-05-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_post_feed_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfeedindex',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, db_column='UPDATED_AT', null=True, verbose_name='Atualizado em'),
        ),
    ]
