# Generated by Django 5.0.3 on 2024-05-13 19:02

import image_optimizer.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_postfeedindex_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmedia',
            name='image',
            field=image_optimizer.fields.OptimizedImageField(db_column='PATH', upload_to='post/media', verbose_name='Imagem'),
        ),
    ]
