# Generated by Django 5.0.3 on 2024-04-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TesteModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('code2', models.CharField(max_length=20)),
                ('test', models.TextField(blank=True)),
            ],
        ),
    ]
