# Generated by Django 5.0.3 on 2024-05-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_delete_testemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
